version: "3.7"

services:
  app:
    build: .
    ports:
      - "8084:8084"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/file_handling
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ommithari

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ommithari
      MYSQL_DATABASE: file_handling
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

# Named volume for persistence
volumes:
  mysql_data: