spring.application.name=File_Handling
server.port=${PORT}
server.address=0.0.0.0


# AWS
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}
cloud.aws.region.static=${AWS_REGION}
aws.bucket.name=orderfilestorage 

# Eureka (use deployed URL, not localhost)
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# MySQL (Render env variables)

spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}


spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
