spring.application.name=File_Handling
server.port=8084

# AWS
aws.accessKey=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION}
aws.bucket.name=orderfilestorage

# Eureka (use deployed URL, not localhost)
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# MySQL (Render env variables)
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect